### PR TITLE
The (parameterized) gradual guarantee proof

### PR DESCRIPTION
**Pull request by cty12**
Hello,
I just finished the parameterized proof for the _gradual guarantee_ , and instantiated it for `GroundInertX` (the representation in the _Refined Criteria_ paper, that is, _Lazy-UD_ type-based cast) and `GroundCast`. 

To facilitate the changes mentioned above, I made the following revision to the code base:

1. Binders are built directly into the branches of `case` for both the surface language and CC. For example, `case L M N` instead of `case L (λ M) (λ N)`. Term definitions are updated to the ones in the `master` branch, that is, ABT for GTLC and intrinsic for CC. 
2. I split the CC (and its compilation from surface) into 2 variants - the vanilla one and one with an additional clause `wrap`, which signifies term wrapped with an inert cast. This helps when defining the precision relation between terms with (inert) casts on one or both sides. 
3. The records `PreCastStructWithSafety` and `PreCastStructWithPrecision` extend `PreCastStruct` with respective definitions and lemmas used in the blame safety proof and the gradual guarantee proof. `CastStructWithSafety` and `CastStructWithPrecision` extend `CastStruct` in a similar fashion. For example, those cast representations without a gradual guarantee proof (yet) do not instantiate `CastStructWithPrecision`. 

**Caveats:** 
1. The parameterized gradual guarantee proof, since is large, is split into 3 files:  auxiliary lemmas about simulation go into `ParamGradualGuaranteeAux` and `ParamGradualGuaranteeSim`; the main simulation theorem is defined & proved in `ParamGradualGuarantee`. 
2. The `wip` branch is my working branch so please choose not to delete it when merging on GitHub. Thank you! :-)

### CODE REVIEW

**Comment by jsiek** [comment]
I'll take a look at this soon.

Do all the old and new files pass checking with Agda?

**Comment by cty12** [comment]
> I'll take a look at this soon.

Thank you!

> Do all the old and new files pass checking with Agda?

Yes. All files referred in `Makefile` pass type checking. You can simply `make clean && make`. :-)

**Review by jsiek — APPROVED** [review]
This is great! Excellent work Tianyu!

**Comment by cty12** [comment]
> This is great! Excellent work Tianyu!

Great! :-)

I'll go ahead and close the PR then. Thank you for reviewing!

**Pull request merged**
